# Generado por defecto
spring.application.name=banking

# Todo esto es la configuración de la aplicación:

# Servidor
server.port=8080

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:bankingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Consola H2 (para ver la BD en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
jwt.secret=c2VjcmV0b211eWxhcmdvcGFyYWphdmFzcHJpbmdib290and0
jwt.expiration=86400000