spring.application.name=banking

server.port=8080

spring.datasource.url=jdbc:h2:mem:bankingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=c2VjcmV0b211eWxhcmdvcGFyYWphdmFzcHJpbmdib290and0
jwt.expiration=86400000
