spring.application.name=banking
server.port=8080
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=true
jwt.secret=c2VjcmV0b211eWxhcmdvcGFyYWphdmFzcHJpbmdib290and0
jwt.expiration=86400000
jwt.refresh-expiration=604800000